/* MathClans V2.1.1 live multiplayer clans + leader-approved membership */
(() => {
'use strict';
const $=q=>document.querySelector(q);
const panel=$('#onlineClanPanel'),status=$('#onlineClanStatus'),hint=$('#onlineClanHint'),actions=$('#onlineClanActions');
if(!panel)return;
let auth,db,rtdb,user=null,clan=null,memberUnsub=null,playerDocUnsub=null,presenceUnsub=null,readyUnsub=null,inviteUnsub=null,battleUnsub=null,challengeUnsub=null,profiles=new Map(),memberRows=[],presence={},ready={},activeInviteId=null,activeBattleId=null,activeChallengeId=null;
const regions=['Central','Tampines','Sengkang','Jurong','Woodlands','Bedok','Punggol','Bishan'];
const guardians=['🐉','🐙','🦊','🐼','🦉','🐢','🦁','🦄'];
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function gameToast(m){window.MathClansGame?.toast?.(m)}
function onlineMode(){return Boolean(window.MathClansOnline?.configured && window.MathClansOnline?.user?.())}
function liveClan(){return Boolean(user&&clan&&state?.player?.clanId===clan.id)}
function updatePanel(){
 if(!user){status.textContent='Sign in to use real clans';hint.textContent='Your local demo clan remains available until you sign in.';actions.innerHTML='<button class="primary" id="clanSignIn">Sign In</button>';$('#clanSignIn').onclick=()=>window.MathClansOnline?.signIn?.();return}
 if(!clan){status.textContent='No online clan yet';hint.textContent='Create a clan or request to join an existing clan. Leaders approve new members. Maximum 30 members per clan.';actions.innerHTML='<button class="secondary" id="browseClans">Browse Clans</button><button class="primary" id="createClan">Create Clan</button>';$('#createClan').onclick=openCreate;$('#browseClans').onclick=openBrowse;return}
 status.textContent=`${clan.guardian||'🐉'} ${clan.name} · ${clan.memberCount||memberRows.length}/30 members`;hint.textContent=`${state.player.clanRole==='leader'?'Clan Leader':state.player.clanRole==='officer'?'Officer':'Member'} · ${clan.region} · Rating ${clan.rating||1500}`;
 actions.innerHTML='<button class="secondary" id="warReadyToggle">⚔ War Ready</button><button class="secondary" id="browseClans">Clan Directory</button>'+((state.player.clanRole==='leader')?'<button class="secondary" id="clanApplications">📨 Applications</button>':'')+'<button class="primary" id="leaveClan">Leave Clan</button>';
 $('#warReadyToggle').onclick=toggleReady;$('#browseClans').onclick=openBrowse;const ap=$('#clanApplications');if(ap)ap.onclick=openApplications;$('#leaveClan').onclick=leaveClan;
}
function openCreate(){
 showModal(`<span class="eyebrow">CREATE ONLINE CLAN</span><h3>Found a new clan</h3><p>Each clan can have up to <b>30 members</b>. You become the clan leader.</p><label>Clan name</label><input id="newClanName" maxlength="28" placeholder="e.g. Math Dragons"><label>Guardian</label><select id="newClanGuardian">${guardians.map(x=>`<option>${x}</option>`).join('')}</select><label>HQ region</label><select id="newClanRegion">${regions.map(x=>`<option>${x}</option>`).join('')}</select><div class="modal-actions"><button class="secondary" onclick="closeModal()">Cancel</button><button class="primary" id="confirmCreateClan">Create Clan</button></div>`);
 $('#confirmCreateClan').onclick=createClan;
}
async function createClan(){
 if(!user||state.player.clanId)return;const name=$('#newClanName').value.trim();if(name.length<3){gameToast('Clan name must have at least 3 characters.');return}
 const guardian=$('#newClanGuardian').value,region=$('#newClanRegion').value,ref=db.collection('clans').doc();const batch=db.batch();
 batch.set(ref,{name,nameLower:name.toLowerCase(),guardian,region,rating:1500,influence:0,memberCount:1,leaderId:user.uid,createdAt:firebase.firestore.FieldValue.serverTimestamp()});
 batch.set(ref.collection('members').doc(user.uid),{uid:user.uid,role:'leader',displayName:state.player.name,avatar:state.player.avatar,joinedAt:firebase.firestore.FieldValue.serverTimestamp()});
 batch.set(db.collection('players').doc(user.uid),{clanId:ref.id,clanRole:'leader',updatedAtMs:Date.now()},{merge:true});
 try{await batch.commit();state.player.clanId=ref.id;state.player.clanRole='leader';save();closeModal();await loadClan(ref.id);gameToast('🏰 Online clan created.')}catch(e){console.error(e);gameToast('Could not create clan. Check Firestore rules.')}
}
async function openBrowse(){
 if(!user)return;showModal('<span class="eyebrow">CLAN DIRECTORY · V2.1.1</span><h3>Online Clans</h3><p>Joining is by application. The clan leader decides whether to accept a new member.</p><div id="cloudClanList">Loading…</div><div class="modal-actions"><button class="secondary" onclick="closeModal()">Close</button></div>');
 try{
   const snap=await db.collection('clans').orderBy('createdAt','desc').limit(30).get(),requestStates={};
   if(!state.player.clanId){await Promise.all(snap.docs.map(async d=>{try{const r=await d.ref.collection('joinRequests').doc(user.uid).get();if(r.exists)requestStates[d.id]=r.data()?.status||'pending'}catch(e){}}))}
   const list=$('#cloudClanList');if(snap.empty){list.innerHTML='<p>No clans yet. Be the first to create one.</p>';return}
   list.innerHTML=snap.docs.map(d=>{const x=d.data(),rs=requestStates[d.id];let join='';if(state.player.clanId===d.id)join='<b>YOUR CLAN</b>';else if(!state.player.clanId){join=rs==='pending'?'<button class="secondary" disabled>REQUEST PENDING</button>':rs==='rejected'?'<button class="secondary request-cloud-clan" data-id="'+d.id+'">Request Again</button>':'<button class="secondary request-cloud-clan" data-id="'+d.id+'">Request to Join</button>'}return `<div class="cloud-clan-row"><span class="cloud-clan-crest">${x.guardian||'🐉'}</span><div><strong>${esc(x.name)}</strong><small>${esc(x.region)} · ${x.memberCount||0}/30 · Rating ${x.rating||1500}</small></div>${join}<button class="secondary report-cloud-clan" data-id="${d.id}" data-name="${esc(x.name)}">🚩</button></div>`}).join('');
   document.querySelectorAll('.request-cloud-clan').forEach(b=>b.onclick=()=>requestJoinClan(b.dataset.id));document.querySelectorAll('.report-cloud-clan').forEach(b=>b.onclick=()=>window.MathClansAdmin?.report?.('clan',b.dataset.id,b.dataset.name));
 }catch(e){console.error(e);$('#cloudClanList').innerHTML='<p>Could not load clans. Check Firestore rules.</p>'}
}
async function requestJoinClan(id){if(!user||state.player.clanId)return;try{const cref=db.collection('clans').doc(id),cs=await cref.get();if(!cs.exists)throw new Error('Clan no longer exists.');const c=cs.data()||{};if(Number(c.memberCount||0)>=30)throw new Error('Clan is full (30/30).');await cref.collection('joinRequests').doc(user.uid).set({uid:user.uid,displayName:state.player.name,avatar:state.player.avatar,status:'pending',requestedAtMs:Date.now(),requestedAt:firebase.firestore.FieldValue.serverTimestamp()});gameToast('📨 Join request sent to the clan leader.');openBrowse()}catch(e){console.error(e);gameToast(e.message||'Could not send join request.')}}
async function openApplications(){if(!user||!clan||state.player.clanRole!=='leader')return;showModal('<span class="eyebrow">CLAN APPLICATIONS · V2.1.1</span><h3>Pending applications</h3><p>You may accept or reject new applicants. Existing members cannot be removed by the clan leader.</p><div id="clanApplicationList">Loading…</div><div class="modal-actions"><button class="secondary" onclick="closeModal()">Close</button></div>');try{const s=await db.collection('clans').doc(clan.id).collection('joinRequests').where('status','==','pending').limit(50).get(),box=$('#clanApplicationList');box.innerHTML=s.empty?'<p>No pending applications.</p>':s.docs.map(d=>{const x=d.data()||{};return `<div class="cloud-clan-row"><span class="cloud-clan-crest">${x.avatar||'🐲'}</span><div><strong>${esc(x.displayName||'Mathling')}</strong><small>Requested to join your clan</small></div><button class="primary accept-clan-app" data-id="${d.id}">Accept</button><button class="secondary reject-clan-app" data-id="${d.id}">Reject</button></div>`}).join('');box.querySelectorAll('.accept-clan-app').forEach(b=>b.onclick=()=>acceptApplication(b.dataset.id));box.querySelectorAll('.reject-clan-app').forEach(b=>b.onclick=()=>rejectApplication(b.dataset.id));}catch(e){console.error(e);$('#clanApplicationList').innerHTML='<p>Could not load applications.</p>'}}
async function acceptApplication(uid){if(!user||!clan||state.player.clanRole!=='leader')return;const cref=db.collection('clans').doc(clan.id),rref=cref.collection('joinRequests').doc(uid),mref=cref.collection('members').doc(uid),pref=db.collection('players').doc(uid);try{await db.runTransaction(async tx=>{const [cs,rs,ps]=await Promise.all([tx.get(cref),tx.get(rref),tx.get(pref)]);if(!cs.exists||!rs.exists)throw new Error('Application no longer exists.');const c=cs.data()||{},r=rs.data()||{},p=ps.data()||{};if(r.status!=='pending')throw new Error('Application already handled.');if(Number(c.memberCount||0)>=30)throw new Error('Clan is full (30/30).');if(p.clanId)throw new Error('Applicant has already joined another clan.');tx.set(mref,{uid,role:'member',displayName:r.displayName||p.displayName||'Mathling',avatar:r.avatar||p.avatar||'🐲',joinedAt:firebase.firestore.FieldValue.serverTimestamp()});tx.update(cref,{memberCount:Number(c.memberCount||0)+1});tx.set(pref,{clanId:clan.id,clanRole:'member',updatedAtMs:Date.now()},{merge:true});tx.delete(rref)});profiles.delete(uid);const ms=await cref.collection('members').get();memberRows=ms.docs.map(d=>d.data());clan.memberCount=memberRows.length;updatePanel();await rebuildRoster();gameToast('✅ Applicant accepted. Member roster updated.');openApplications()}catch(e){console.error(e);gameToast(e.message||'Could not accept applicant.')}}
async function rejectApplication(uid){if(!user||!clan||state.player.clanRole!=='leader')return;try{await db.collection('clans').doc(clan.id).collection('joinRequests').doc(uid).set({status:'rejected',decidedAtMs:Date.now(),decidedBy:user.uid},{merge:true});gameToast('Application rejected.');openApplications()}catch(e){console.error(e);gameToast('Could not reject application.')}}
async function leaveClan(){
 if(!clan||!user)return;if(!confirm(`Leave ${clan.name}?`))return;
 const cref=db.collection('clans').doc(clan.id),mref=cref.collection('members').doc(user.uid),pref=db.collection('players').doc(user.uid);
 try{
   const memberSnap=await cref.collection('members').orderBy('joinedAt','asc').get();
   const remaining=memberSnap.docs.filter(d=>d.id!==user.uid);
   if(remaining.length===0){
     const batch=db.batch();batch.delete(mref);batch.delete(cref);batch.set(pref,{clanId:null,clanRole:null,updatedAtMs:Date.now()},{merge:true});await batch.commit();
   }else if(state.player.clanRole==='leader'){
     const nextDoc=remaining[0],nextUid=nextDoc.id;
     await db.runTransaction(async tx=>{const cs=await tx.get(cref);const c=cs.data()||{};tx.update(cref,{leaderId:nextUid,memberCount:Math.max(1,(c.memberCount||remaining.length+1)-1)});tx.update(nextDoc.ref,{role:'leader'});tx.delete(mref);tx.set(pref,{clanId:null,clanRole:null,updatedAtMs:Date.now()},{merge:true})});
   }else{
     await db.runTransaction(async tx=>{const cs=await tx.get(cref);const c=cs.data()||{};tx.delete(mref);tx.update(cref,{memberCount:Math.max(0,(c.memberCount||1)-1)});tx.set(pref,{clanId:null,clanRole:null,updatedAtMs:Date.now()},{merge:true})});
   }
   await rtdb.ref(`warReady/${user.uid}`).remove();state.player.clanId=null;state.player.clanRole=null;save();stopWatchers();clan=null;memberRows=[];presence={};ready={};window.MathClansGame?.setMembers?.([]);window.MathClansGame?.setPlayerClan?.(null,null);updatePanel();gameToast('Left clan.');
 }catch(e){console.error(e);gameToast(e.message||'Could not leave clan.')}
}
async function toggleReady(){if(!user||!clan)return;const ref=rtdb.ref(`warReady/${user.uid}`);const snap=await ref.once('value');if(snap.exists()&&snap.val()?.ready){await ref.remove();gameToast('War Ready off.')}else{await ref.set({ready:true,clanId:clan.id,lastChanged:firebase.database.ServerValue.TIMESTAMP});gameToast('⚔ War Ready on.')}}

function rallyId(){return `${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`}
async function startRally(selected,targetIndex,onComplete){
 if(!user||!clan||!selected?.length)return;
  const id=rallyId(),selectedByUid=Object.fromEntries(selected.filter(x=>x.uid).map(x=>[x.uid,x]));
 // The caller has already volunteered by starting the rally, so auto-accept if selected.
 const responses={};if(selectedByUid[user.uid])responses[user.uid]='accepted';
 const rally={id,clanId:clan.id,callerUid:user.uid,targetIndex,createdAt:firebase.database.ServerValue.TIMESTAMP,expiresAt:Date.now()+20000,status:'open',selected:Object.keys(selectedByUid),responses};
 const updates={};updates[`warRallies/${clan.id}/${id}`]=rally;
 for(const uid of Object.keys(selectedByUid)){if(uid===user.uid)continue;updates[`rallyInvites/${uid}/${id}`]={rallyId:id,clanId:clan.id,clanName:clan.name,callerUid:user.uid,targetIndex,expiresAt:Date.now()+20000};}
 await rtdb.ref().update(updates);
 showRallyOwner(id,selected,selectedByUid,onComplete);
}
function showRallyOwner(id,selected,selectedByUid,onComplete){
 const ref=rtdb.ref(`warRallies/${clan.id}/${id}`),deadline=Date.now()+20000;let done=false,timer=null;
 const finish=async(data)=>{if(done)return;done=true;if(timer)clearInterval(timer);ref.off();const responses=data?.responses||{};const acceptedEntries=selected.filter(x=>!x.uid||responses[x.uid]==='accepted');const accepted=acceptedEntries.map(x=>x.idx);const cleanup={};for(const uid of Object.keys(selectedByUid)){cleanup[`rallyInvites/${uid}/${id}`]=null}cleanup[`warRallies/${clan.id}/${id}/status`]='closed';await rtdb.ref().update(cleanup).catch(()=>{});closeModal();onComplete?.({indices:accepted,entries:acceptedEntries,rallyId:id})};
 const render=data=>{const responses=data?.responses||{},known=Object.keys(selectedByUid),answered=known.filter(uid=>responses[uid]==='accepted'||responses[uid]==='rejected').length;const remaining=Math.max(0,Math.ceil((deadline-Date.now())/1000));showModal(`<span class="eyebrow">RALLY FOR WAR</span><h3>Waiting for clan responses</h3><p>Maximum wait: <b>20 seconds</b>. The rally closes immediately when everyone responds.</p><div class="rally-box"><div class="rally-countdown">${remaining}s</div><div class="rally-roster">${selected.map(x=>{const st=x.uid?(responses[x.uid]||'pending'):'accepted';return `<div class="rally-row"><span>${x.avatar||'🐲'}</span><b>${esc(x.name||'Mathling')}</b><span class="rally-state ${st}">${st.toUpperCase()}</span></div>`}).join('')}</div></div><div class="modal-actions"><button class="secondary" id="cancelRallyBtn">Cancel Rally</button></div>`);const b=$('#cancelRallyBtn');if(b)b.onclick=()=>finish({responses:{}});if(answered===known.length&&known.length>0)finish(data);};
 ref.on('value',snap=>{const data=snap.val()||{};render(data)});
 timer=setInterval(async()=>{const snap=await ref.once('value'),data=snap.val()||{};if(Date.now()>=deadline)finish(data);else render(data)},1000);
}
function watchRallyInvites(){
 if(inviteUnsub){inviteUnsub();inviteUnsub=null}if(!user)return;const ref=rtdb.ref(`rallyInvites/${user.uid}`);
 const handler=snap=>{const all=snap.val()||{},entries=Object.entries(all).filter(([,v])=>v&&v.expiresAt>Date.now()).sort((a,b)=>a[1].expiresAt-b[1].expiresAt);if(!entries.length)return;const [id,inv]=entries[0];if(activeInviteId===id)return;activeInviteId=id;showInvite(id,inv)};
 ref.on('value',handler);inviteUnsub=()=>ref.off('value',handler);
}
function showInvite(id,inv){
 const deadline=Number(inv.expiresAt||Date.now()+20000);let timer=null,resolved=false;
 const respond=async(choice)=>{if(resolved)return;resolved=true;if(timer)clearInterval(timer);await rtdb.ref(`warRallies/${inv.clanId}/${id}/responses/${user.uid}`).set(choice);await rtdb.ref(`rallyInvites/${user.uid}/${id}`).remove();activeInviteId=null;closeModal();gameToast(choice==='accepted'?'⚔ Rally accepted. Prepare for war.':'Rally declined.');};
 const draw=()=>{const remain=Math.max(0,Math.ceil((deadline-Date.now())/1000));if(remain<=0){respond('rejected');return}showModal(`<span class="eyebrow">⚔ RALLY FOR WAR</span><h3>${esc(inv.clanName||'Your clan')} is calling you</h3><p>You were selected for a clan battle. Participation is voluntary.</p><div class="rally-box"><div class="rally-countdown">${remain}s</div><p>Accept to rally for war, or reject this invitation.</p></div><div class="modal-actions"><button class="secondary" id="rallyReject">Reject</button><button class="primary" id="rallyAccept">Accept</button></div>`);$('#rallyReject').onclick=()=>respond('rejected');$('#rallyAccept').onclick=()=>respond('accepted')};draw();timer=setInterval(draw,1000);
}

function battleId(){return `battle-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`}
async function createBattleSession(enemy,formation,team){
 if(!user||!clan||!team?.length)return null;
 const id=battleId(),participants={};
 for(const m of team){if(!m?.uid)continue;participants[m.uid]={uid:m.uid,name:m.name||'Mathling',avatar:m.avatar||'🐲',skills:m.skills||{},status:'deployed',scoreTotal:0,asked:0,correct:0,lastWaveScore:0,lastSeen:firebase.database.ServerValue.TIMESTAMP}}
 if(!Object.keys(participants).length)return null;
 const data={id,clanId:clan.id,clanName:clan.name,ownerUid:user.uid,enemy:{name:enemy.name,crest:enemy.crest,region:enemy.region,rating:enemy.rating,skills:enemy.skills||{}},formation,participants,startedAt:Date.now(),endsAt:Date.now()+90000,status:'active'};
 await rtdb.ref(`activeBattles/${id}`).set(data);activeBattleId=id;return data;
}
function participantAverage(p){if(!p||p.forfeit||p.status==='left')return 0;return Number(p.asked||0)>0?Number(p.scoreTotal||0)/Number(p.asked||1):0}
function sideMetrics(root,side){const uids=Object.keys(root?.sides?.[side]?.participants||{}),ps=uids.map(uid=>root?.participants?.[uid]||root?.sides?.[side]?.participants?.[uid]||{});if(!ps.length)return{teamAvg:0,accuracy:0,skills:{algebra:1,geometry:1,trigonometry:1,statistics:1}};const teamAvg=ps.reduce((a,p)=>a+participantAverage(p),0)/ps.length,totalAsked=ps.reduce((a,p)=>a+Number(p.asked||0),0),totalCorrect=ps.reduce((a,p)=>a+(p.forfeit||p.status==='left'?0:Number(p.correct||0)),0),skills={};for(const k of ['algebra','geometry','trigonometry','statistics'])skills[k]=ps.reduce((a,p)=>a+Number(p.skills?.[k]||1),0)/ps.length;return{teamAvg,accuracy:totalAsked?100*totalCorrect/totalAsked:0,skills}}
function formationFactor(sideData,m){const f=sideData?.formation||'balanced',s=m.skills||{},base=(Number(s.algebra||1)+Number(s.geometry||1)+Number(s.trigonometry||1)+Number(s.statistics||1))/4;let emphasis=base;if(f==='assault')emphasis=Number(s.algebra||base);if(f==='fortress')emphasis=Number(s.geometry||base);if(f==='precision')emphasis=Number(s.trigonometry||base);if(f==='tactical')emphasis=Number(s.statistics||base);return 1+Math.min(.15,Math.max(0,emphasis)/(Math.max(0,emphasis)+180)*.15)}
function computeBattleState(root,now=Date.now()){const a=sideMetrics(root,'attacker'),d=sideMetrics(root,'defender'),aPower=a.teamAvg*formationFactor(root.sides?.attacker,a),dPower=d.teamAvg*formationFactor(root.sides?.defender,d),total=Math.max(1,aPower+dPower),elapsed=Math.max(0,Math.min(1,(now-Number(root.startedAt||now))/Math.max(1000,Number(root.endsAt||now+90000)-Number(root.startedAt||now)))),aEnd=dPower>aPower?0:Math.max(1000,Math.round(10000*(.25+.5*(aPower/total)))),dEnd=aPower>dPower?0:Math.max(1000,Math.round(10000*(.25+.5*(dPower/total))));return{attacker:{teamAvg:a.teamAvg,accuracy:a.accuracy,finalPower:aPower,hp:Math.max(0,Math.round(10000-(10000-aEnd)*elapsed))},defender:{teamAvg:d.teamAvg,accuracy:d.accuracy,finalPower:dPower,hp:Math.max(0,Math.round(10000-(10000-dEnd)*elapsed))}}}
async function reportBattleScore(id,score,correct,elapsed){if(!user||!id)return;await rtdb.ref(`activeBattles/${id}`).transaction(root=>{if(!root||root.result||root.status==='ended'||!root.participants?.[user.uid])return root;const p=root.participants[user.uid];if(p.forfeit||p.status==='left')return root;p.status='active';p.lastWaveScore=Number(score||0);p.scoreTotal=Number(p.scoreTotal||0)+Number(score||0);p.asked=Number(p.asked||0)+1;p.correct=Number(p.correct||0)+(correct?1:0);p.lastElapsed=Number(elapsed||0);p.avgScore=p.scoreTotal/Math.max(1,p.asked);p.lastSeen=Date.now();root.scoreboard=computeBattleState(root,Date.now());return root}).catch(()=>{})}
async function markSharedParticipantLeft(id,uid){if(!id||!uid)return;await rtdb.ref(`activeBattles/${id}`).transaction(root=>{if(!root||root.result||!root.participants?.[uid])return root;root.participants[uid].status='left';root.participants[uid].forfeit=true;root.participants[uid].scoreTotal=0;root.participants[uid].avgScore=0;root.participants[uid].lastWaveScore=0;root.participants[uid].lastSeen=Date.now();root.scoreboard=computeBattleState(root,Date.now());return root}).catch(()=>{})}
function ratingDeltas(root,winner){if(winner==='draw')return{attacker:0,defender:0};const ar=Number(root.sides?.attacker?.rating||1500),dr=Number(root.sides?.defender?.rating||1500),win=winner,lose=winner==='attacker'?'defender':'attacker',wr=win==='attacker'?ar:dr,lr=lose==='attacker'?ar:dr,bonus=Math.max(-6,Math.min(8,Math.round((lr-wr)/80))),gain=20+bonus,loss=-(16+Math.max(-4,Math.min(6,Math.round((wr-lr)/100))));return{[win]:gain,[lose]:loss}}
function buildResult(root){const sb=computeBattleState(root,Number(root.endsAt||Date.now())),a=sb.attacker,d=sb.defender;let winner='draw';if(Math.abs(a.finalPower-d.finalPower)>.01)winner=a.finalPower>d.finalPower?'attacker':'defender';const delta=ratingDeltas(root,winner);if(winner==='attacker'){a.hp=Math.max(1,a.hp);d.hp=0}else if(winner==='defender'){d.hp=Math.max(1,d.hp);a.hp=0}return{winner,completedAt:Date.now(),sides:{attacker:a,defender:d},ratingDelta:delta}}
async function finalizeBattle(id){if(!id)return;await rtdb.ref(`activeBattles/${id}`).transaction(root=>{if(!root||root.result)return root;const now=Date.now(),ps=Object.values(root.participants||{}),allDone=ps.length&&ps.every(p=>p.status==='finished'||p.status==='left');if(now<Number(root.endsAt||0)&&!allDone)return root;root.scoreboard=computeBattleState(root,Number(root.endsAt||now));root.result=buildResult(root);root.status='ended';root.endedAt=now;return root}).catch(()=>{})}
async function applyResultSide(id,data){if(!user||!clan||!data?.result)return;const side=data.sides?.attacker?.clanId===clan.id?'attacker':data.sides?.defender?.clanId===clan.id?'defender':null;if(!side)return;const claim=await rtdb.ref(`battleResultClaims/${id}/${clan.id}`).transaction(v=>v||{uid:user.uid,at:Date.now()});if(claim.committed&&claim.snapshot.val()?.uid===user.uid){const delta=Number(data.result.ratingDelta?.[side]||0),won=data.result.winner===side;try{await db.runTransaction(async tx=>{const ref=db.collection('clans').doc(clan.id),snap=await tx.get(ref);if(!snap.exists)return;const c=snap.data()||{};tx.update(ref,{rating:Math.max(1000,Number(c.rating||1500)+delta),influence:Math.max(0,Math.min(100,Number(c.influence||0)+(won?2:0)))})})}catch(e){console.warn('Rating update failed',e)}}const hclaim=await rtdb.ref(`battleHistoryClaims/${id}`).transaction(v=>v||{uid:user.uid,at:Date.now()});if(hclaim.committed&&hclaim.snapshot.val()?.uid===user.uid){const participantUids=Object.keys(data.participants||{});db.collection('battleHistory').doc(id).set({battleId:id,attackerClanId:data.sides?.attacker?.clanId,attackerClanName:data.sides?.attacker?.clanName,defenderClanId:data.sides?.defender?.clanId,defenderClanName:data.sides?.defender?.clanName,winner:data.result.winner,ratingDelta:data.result.ratingDelta,sides:data.result.sides,participantUids,startedAtMs:Number(data.startedAt||0),endedAtMs:Number(data.endedAt||Date.now()),createdAt:firebase.firestore.FieldValue.serverTimestamp()}).catch(e=>console.warn('History write failed',e))}}
async function finishBattleForPlayer(id){if(!user||!id)return;const base=rtdb.ref(`activeBattles/${id}`);await base.child(`participants/${user.uid}`).update({status:'finished',lastSeen:firebase.database.ServerValue.TIMESTAMP}).catch(()=>{});await finalizeBattle(id)}
function watchActiveBattles(){if(battleUnsub){battleUnsub();battleUnsub=null}if(!user||!clan)return;const ref=rtdb.ref('activeBattles');const handler=snap=>{const all=snap.val()||{};let found=null;for(const [id,b] of Object.entries(all)){if((b?.status==='active'||b?.status==='deploying'||b?.status==='ended')&&b?.participants?.[user.uid]&&(!b.result||Number(b?.endedAt||Date.now())>Date.now()-120000)){found={id,...b};break}}if(!found)return;activeBattleId=found.id;if(found.result){window.MathClansGame?.syncSharedBattle?.(found.id,found);applyResultSide(found.id,found).catch(()=>{});return}window.MathClansOnline?.setActivity?.('battle');if(found.status==='deploying'&&Date.now()<Number(found.battleStartsAt||0)){showDeployment(found.id,found);return}if(found.status==='deploying')rtdb.ref(`activeBattles/${found.id}`).update({status:'active'}).catch(()=>{});window.MathClansGame?.joinSharedBattle?.(found.id,{...found,status:'active'});window.MathClansGame?.syncSharedBattle?.(found.id,found);if(Date.now()>=Number(found.endsAt||0))finalizeBattle(found.id)};ref.on('value',handler);battleUnsub=()=>ref.off('value',handler)}
async function rebuildRoster(){if(!clan)return;const rows=[];for(const m of memberRows){let p=profiles.get(m.uid);if(!p){try{const ps=await db.collection('players').doc(m.uid).get();p=ps.data()||{};profiles.set(m.uid,p)}catch(e){p={}}}const pr=presence[m.uid]||{},wr=ready[m.uid]||{};let status='offline';if(pr.state==='online'||pr.state==='away')status=wr.ready?'ready':pr.activity==='training'?'training':pr.activity==='battle'?'deployed':'online';rows.push({uid:m.uid,name:m.displayName||p.displayName||'Mathling',avatar:m.avatar||p.avatar||'🐲',role:roleFromSkills(p.skills),status,skills:{algebra:p.skills?.algebra||1,geometry:p.skills?.geometry||1,trigonometry:p.skills?.trigonometry||1,statistics:p.skills?.statistics||1}})}window.MathClansGame?.setMembers?.(rows);window.MathClansGame?.setClan?.({...clan,memberCount:rows.length});}
function startRealtime(){if(presenceUnsub)presenceUnsub();if(readyUnsub)readyUnsub();const pref=rtdb.ref('presence'),wref=rtdb.ref('warReady');const ph=s=>{const prev=presence;presence=s.val()||{};for(const uid of Object.keys(prev||{})){if((prev[uid]?.state==='online'||prev[uid]?.state==='away')&&presence[uid]?.state==='offline')window.MathClansGame?.markBattleParticipantLeft?.(uid)}rebuildRoster()},wh=s=>{ready=s.val()||{};rebuildRoster()};pref.on('value',ph);wref.on('value',wh);presenceUnsub=()=>pref.off('value',ph);readyUnsub=()=>wref.off('value',wh)}
function stopWatchers(){if(memberUnsub)memberUnsub();if(presenceUnsub)presenceUnsub();if(readyUnsub)readyUnsub();if(inviteUnsub)inviteUnsub();if(battleUnsub)battleUnsub();if(challengeUnsub)challengeUnsub();memberUnsub=presenceUnsub=readyUnsub=inviteUnsub=battleUnsub=challengeUnsub=null;profiles.clear();activeBattleId=null}
async function loadClan(id){stopWatchers();if(!id){clan=null;updatePanel();return}try{const ref=db.collection('clans').doc(id),snap=await ref.get();if(!snap.exists){state.player.clanId=null;state.player.clanRole=null;save();clan=null;updatePanel();return}clan={id:snap.id,...snap.data()};window.MathClansGame?.setClan?.(clan);updatePanel();memberUnsub=ref.collection('members').onSnapshot(ms=>{memberRows=ms.docs.map(d=>d.data());const mine=memberRows.find(m=>m.uid===user?.uid);if(mine?.role&&state.player.clanRole!==mine.role){state.player.clanRole=mine.role;save();window.MathClansGame?.setPlayerClan?.(clan.id,mine.role)}clan.memberCount=memberRows.length;updatePanel();rebuildRoster()},e=>console.warn('clan members',e));startRealtime();watchRallyInvites();watchIncomingChallenges();watchActiveBattles();refreshClanRanking()}catch(e){console.error(e);status.textContent='Could not load online clan';hint.textContent='Check Firestore rules and connection.'}}

// ===== V2.0 school-wide rankings + real clan war lobby =====

let lastPlayerRankingAt=0;
async function refreshPlayerRanking(force=false){
 if(!db)return;
 if(!force&&Date.now()-lastPlayerRankingAt<60000)return;
 lastPlayerRankingAt=Date.now();
 try{
   const snap=await db.collection('players').orderBy('totalSkill','desc').limit(100).get();
   const rows=snap.docs.map((d,i)=>{const x=d.data()||{};return{uid:d.id,name:x.displayName||'Mathling',avatar:x.avatar||'🐲',schoolClass:x.schoolClass||'',yearLevel:x.yearLevel||'',totalSkill:Number(x.totalSkill||Object.values(x.skills||{}).reduce((a,b)=>a+Number(b||0),0)),rank:i+1,you:d.id===user?.uid}}).filter(x=>x.totalSkill>0);
   window.MathClansGame?.setPlayerRankings?.(rows);
 }catch(e){console.warn('Player ranking refresh failed',e)}
}

async function refreshClanRanking(){
 if(!db||!clan)return;
 try{
   const snap=await db.collection('clans').orderBy('rating','desc').limit(200).get();
   const rows=snap.docs.map((d,i)=>{const x=d.data()||{};return{id:d.id,name:x.name||'Clan',crest:x.guardian||'🐉',guardian:x.guardian||'🐉',region:x.region||'—',rating:Number(x.rating||1500),memberCount:Number(x.memberCount||0),rank:i+1,you:d.id===clan.id}});
   const mine=rows.find(x=>x.id===clan.id);if(mine){clan.ranking=mine.rank;window.MathClansGame?.setClan?.({...clan,ranking:mine.rank})}window.MathClansGame?.setRankings?.(rows);await refreshPlayerRanking();
 }catch(e){console.warn('Ranking refresh failed',e)}
}
async function getWarTargets(){
 if(!db||!clan)return[];
 const snap=await db.collection('clans').orderBy('rating','desc').limit(50).get();
 const rows=snap.docs.map((d,i)=>{const x=d.data()||{};return{id:d.id,name:x.name||'Clan',crest:x.guardian||'🐉',guardian:x.guardian||'🐉',region:x.region||'—',rating:Number(x.rating||1500),memberCount:Number(x.memberCount||0),influence:Number(x.influence||0),ranking:i+1}}).filter(x=>x.id!==clan.id&&x.memberCount>0);
 return rows;
}
function challengeId(){return `war-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`}
function teamToParticipants(team,side){const out={};for(const m of team||[]){if(!m?.uid)continue;out[m.uid]={uid:m.uid,name:m.name||'Mathling',avatar:m.avatar||'🐲',skills:m.skills||{},side:side||null,status:'deploying',scoreTotal:0,asked:0,correct:0,lastWaveScore:0,avgScore:0,forfeit:false}}return out}
async function createWarChallenge(enemy,formation,attackerTeam){
 if(!user||!clan||!enemy?.id||!attackerTeam?.length)throw new Error('Missing war challenge data');
 const id=challengeId(),expiresAt=Date.now()+60000;
 const data={id,status:'awaiting_defender',createdAt:firebase.database.ServerValue.TIMESTAMP,expiresAt,attacker:{clanId:clan.id,clanName:clan.name,guardian:clan.guardian||'🐉',region:clan.region,rating:Number(clan.rating||1500),formation,callerUid:user.uid,participants:teamToParticipants(attackerTeam,'attacker')},defender:{clanId:enemy.id,clanName:enemy.name,guardian:enemy.guardian||enemy.crest||'🐉',region:enemy.region,rating:Number(enemy.rating||1500)},targetClanId:enemy.id};
 const updates={};updates[`warChallenges/${id}`]=data;updates[`clanWarInbox/${enemy.id}/${id}`]={challengeId:id,fromClanId:clan.id,fromClanName:clan.name,expiresAt};await rtdb.ref().update(updates);
 showOutgoingChallenge(id,data);return{id};
}
function showOutgoingChallenge(id,seed){
 const ref=rtdb.ref(`warChallenges/${id}`);let timer=null,done=false;
 const close=()=>{if(done)return;done=true;if(timer)clearInterval(timer);ref.off('value',handler)};
 const handler=s=>{const d=s.val()||seed,remain=Math.max(0,Math.ceil((Number(d.expiresAt||0)-Date.now())/1000));if(d.status==='rejected'){close();closeModal();gameToast('The rival clan rejected the challenge.');return}if(d.status==='deploying'||d.status==='active'){close();closeModal();gameToast('⚔ Challenge accepted. Troops are deploying.');return}if(remain<=0){close();rtdb.ref(`warChallenges/${id}`).update({status:'expired'}).catch(()=>{});closeModal();gameToast('War challenge expired.');return}showModal(`<span class="eyebrow">V1.8 WAR LOBBY</span><h3>Challenge sent to ${esc(d.defender?.clanName||'rival clan')}</h3><p>Waiting for the defending clan to answer. This challenge expires in <b>${remain}s</b>.</p><div class="war-lobby-status"><div class="war-lobby-side"><span class="crest">${d.attacker?.guardian||'🐉'}</span><div><strong>${esc(d.attacker?.clanName||'Your clan')}</strong><small>${Object.keys(d.attacker?.participants||{}).length} rallied</small></div><b>READY</b></div><div class="war-lobby-side"><span class="crest">${d.defender?.guardian||'🐉'}</span><div><strong>${esc(d.defender?.clanName||'Rival')}</strong><small>Waiting for defender</small></div><b>${remain}s</b></div></div><div class="modal-actions"><button class="secondary" id="cancelChallenge">Withdraw</button></div>`);const b=$('#cancelChallenge');if(b)b.onclick=async()=>{await ref.update({status:'withdrawn'});await rtdb.ref(`clanWarInbox/${d.defender?.clanId}/${id}`).remove();close();closeModal()}};
 ref.on('value',handler);timer=setInterval(async()=>{const s=await ref.once('value');handler(s)},1000);
}
function watchIncomingChallenges(){
 if(challengeUnsub){challengeUnsub();challengeUnsub=null}if(!rtdb||!clan)return;const ref=rtdb.ref(`clanWarInbox/${clan.id}`);
 const handler=async s=>{const all=s.val()||{},now=Date.now();const entries=Object.entries(all).filter(([,v])=>v&&Number(v.expiresAt||0)>now);if(!entries.length)return;const [id]=entries[0];if(activeChallengeId===id)return;const snap=await rtdb.ref(`warChallenges/${id}`).once('value'),d=snap.val();if(!d||d.status!=='awaiting_defender')return;activeChallengeId=id;showIncomingChallenge(id,d)};
 ref.on('value',handler);challengeUnsub=()=>ref.off('value',handler);
}
function showIncomingChallenge(id,d){
 const remain=Math.max(0,Math.ceil((Number(d.expiresAt||0)-Date.now())/1000));if(remain<=0){activeChallengeId=null;return}
 showModal(`<span class="eyebrow">⚔ INCOMING CLAN CHALLENGE</span><h3>${esc(d.attacker?.clanName||'A rival clan')} challenges ${esc(clan.name)}</h3><p>${Object.keys(d.attacker?.participants||{}).length} attacking member${Object.keys(d.attacker?.participants||{}).length===1?'':'s'} are rallied. Accepting starts a 20-second voluntary defence rally for your online clan members.</p><div class="war-lobby-status"><div class="war-lobby-side"><span class="crest">${d.attacker?.guardian||'⚔'}</span><div><strong>${esc(d.attacker?.clanName||'Rival')}</strong><small>Rating ${d.attacker?.rating||1500}</small></div><b>ATTACK</b></div></div><div class="modal-actions"><button class="secondary" id="rejectWarChallenge">Reject</button><button class="primary" id="defendWarChallenge">Defend & Rally</button></div>`);
 $('#rejectWarChallenge').onclick=async()=>{await rtdb.ref(`warChallenges/${id}`).update({status:'rejected',rejectedBy:user.uid});await rtdb.ref(`clanWarInbox/${clan.id}/${id}`).remove();activeChallengeId=null;closeModal()};
 $('#defendWarChallenge').onclick=async()=>{const roster=(window.MathClansGame?.localMembers||[]).map((m,idx)=>({idx,...m})).filter(m=>m.uid&&m.status!=='offline'&&m.status!=='deployed').slice(0,10);if(!roster.length){gameToast('No online defenders are available.');return}closeModal();startRally(roster,id,async result=>{const defenders=result?.entries||[];if(!defenders.length){await rtdb.ref(`warChallenges/${id}`).update({status:'rejected',reason:'no_defenders'});activeChallengeId=null;return}await activateChallenge(id,d,defenders);activeChallengeId=null})};
}
async function activateChallenge(id,d,defenderTeam){
 const attacker=d.attacker||{},defender={clanId:clan.id,clanName:clan.name,guardian:clan.guardian||'🐉',region:clan.region,rating:Number(clan.rating||1500),formation:'balanced',callerUid:user.uid,participants:teamToParticipants(defenderTeam,'defender')};
 const allParticipants={...(attacker.participants||{}),...(defender.participants||{})},battleStartsAt=Date.now()+6000,endsAt=battleStartsAt+90000;
 const session={id,status:'deploying',challengeId:id,ownerUid:attacker.callerUid,creatorUid:user.uid,participants:allParticipants,sides:{attacker,defender},battleStartsAt,startedAt:battleStartsAt,endsAt,scoreboard:{attacker:{hp:10000,teamAvg:0,accuracy:0,finalPower:0},defender:{hp:10000,teamAvg:0,accuracy:0,finalPower:0}},result:null};
 const updates={};updates[`activeBattles/${id}`]=session;updates[`warChallenges/${id}/status`]='deploying';updates[`warChallenges/${id}/sessionId`]=id;updates[`clanWarInbox/${clan.id}/${id}`]=null;await rtdb.ref().update(updates);
 setTimeout(()=>rtdb.ref(`activeBattles/${id}`).update({status:'active'}).catch(()=>{}),6000);
}
function showDeployment(sessionId,data){
 const start=Number(data.battleStartsAt||Date.now());window.MathClansOnline?.setActivity?.('battle');
 const draw=()=>{const remain=Math.max(0,Math.ceil((start-Date.now())/1000));showModal(`<span class="eyebrow">V1.9 TROOP DEPLOYMENT</span><h3>Marching to battle</h3><div class="deployment-countdown">${remain}</div><p class="deployment-note">Both clans are locked into this war session. Battle begins automatically when the deployment countdown reaches zero.</p>`);if(remain<=0){clearInterval(t);rtdb.ref(`activeBattles/${sessionId}`).update({status:'active'}).catch(()=>{});closeModal();window.MathClansGame?.joinSharedBattle?.(sessionId,{...data,status:'active'})}};
 draw();const t=setInterval(draw,1000);
}

function openSettings(){if(!clan||state.player.clanRole!=='leader'){gameToast('Only the clan leader can edit clan settings.');return}showModal(`<span class="eyebrow">ONLINE CLAN SETTINGS</span><h3>Edit ${esc(clan.name)}</h3><label>Clan name</label><input id="cloudClanName" maxlength="28" value="${esc(clan.name)}"><label>Region</label><select id="cloudClanRegion">${regions.map(x=>`<option ${x===clan.region?'selected':''}>${x}</option>`).join('')}</select><div class="modal-actions"><button class="secondary" onclick="closeModal()">Cancel</button><button class="primary" id="saveCloudClan">Save</button></div>`);$('#saveCloudClan').onclick=async()=>{const name=$('#cloudClanName').value.trim();if(name.length<3)return;await db.collection('clans').doc(clan.id).update({name,nameLower:name.toLowerCase(),region:$('#cloudClanRegion').value});clan.name=name;clan.region=$('#cloudClanRegion').value;window.MathClansGame?.setClan?.(clan);closeModal();updatePanel()}}
function initFirebase(){if(!window.MathClansOnline?.configured){updatePanel();return}auth=firebase.auth();db=firebase.firestore();rtdb=firebase.database();auth.onAuthStateChanged(async u=>{user=u||null;if(playerDocUnsub){playerDocUnsub();playerDocUnsub=null}if(!user){stopWatchers();clan=null;updatePanel();return}let first=true;playerDocUnsub=db.collection('players').doc(user.uid).onSnapshot(async ps=>{const pd=ps.data()||{},nextClan=pd.clanId||null,nextRole=pd.clanRole||null,current=clan?.id||null;state.player.clanId=nextClan;state.player.clanRole=nextRole;save();if(nextClan&&nextClan!==current){await loadClan(nextClan);if(!first)gameToast('🏰 Your clan membership has been updated.')}else if(!nextClan&&current){stopWatchers();clan=null;window.MathClansGame?.setMembers?.([]);updatePanel();if(!first)gameToast('You are no longer in that clan.')}else if(nextClan&&current===nextClan){window.MathClansGame?.setPlayerClan?.(nextClan,nextRole||'member');updatePanel()}else{clan=null;updatePanel();await refreshPlayerRanking(true)}first=false},e=>{console.warn('player membership watch',e);updatePanel()})})}
window.MathClansClans={isOnlineMode:onlineMode,isLiveClan:liveClan,openSettings,openBrowse,openApplications,startRally,createBattleSession,reportBattleScore,markSharedParticipantLeft,finishBattleForPlayer,getWarTargets,createWarChallenge,refreshClanRanking,refreshPlayerRanking,finalizeBattle,currentClan:()=>clan};
setTimeout(initFirebase,0);
})();
